spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wanted?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: System123
    driver-class-name: com.mysql.cj.jdbc.Driver
